Pizza/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Pizza.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pizza/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL;
using Domain.ConnectModels;
using Domain.Models;
using Domain.VmModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Pizza.Pages
{
    public class IndexModel : PageModel
    {
        private readonly PizzaDbContext _context;
        private string Category { get; set; } = "";
        private int[] _Meat = new []{1, 2, 8, 9, 17};
        private int _Cheese = 10;

        public int orderID = 0;

        public IndexModel(PizzaDbContext context)
        {
            _context = context;
        }

        public List<PizzaTypeVM> Pizzas = new List<PizzaTypeVM>();

        public void OnGet(string? category,
                            int? orderId)
        {
            Category = category == null ? "" : category;
            if (orderId != null) 
            {
                orderID = orderId.Value;
            }
            List<Lisa> lisas;
            List<PizzaType> pizzaTypes;
            List<PizzaTypeLisaAssignment> pizzaTypeLisas;

            if (_context != null)
            {
                if (_context.Lisas != null)
                {
                    lisas = _context.Lisas.ToList();
                }

                if (_context.PizzaTypes != null && _context.PizzaTypeLisaAssignments != null)
                {
                    pizzaTypeLisas = _context.PizzaTypeLisaAssignments
                        .Include(x=>x.PizzaType)
                        .Include(x=>x.Lisa).
                        ToList();
                    pizzaTypes = _context.PizzaTypes.ToList();

                    foreach (PizzaType pizzaType in pizzaTypes)
                    {
                        var newPizza = new PizzaTypeVM();
                        newPizza.PizzaType = pizzaType;
                        newPizza.Lisas = new List<string>();
                        List<string> Name = new List<string>();
                        foreach (var pizzTypeLisa in pizzaTypeLisas)
                        {
                            if (pizzTypeLisa.Lisa != null && pizzTypeLisa.PizzaTypeId == pizzaType.Id)
                            {
                                newPizza.Lisas.Add(pizzTypeLisa.Lisa.Name);
                                newPizza.LisasInt.Add(pizzTypeLisa.Lisa.Id);
                                Name.Add(pizzTypeLisa.Lisa.Name);
                            }
                        }
                        newPizza.NameLisas = string.Join(", ", Name);
                        Pizzas.Add(newPizza);    
                    }

                }

                if (Category != "")
                {
                    var PizzasToTest = Pizzas;
                    Pizzas = new List<PizzaTypeVM>();
                    if (Category == "Cheese")
                    {
                        foreach (PizzaTypeVM pizza in PizzasToTest)
                        {
                            if (pizza.LisasInt.Contains(_Cheese))
                            {
                                Pizzas.Add(pizza);
                            }
                        }
                    }
                    if (Category == "Vegan")
                    {
                        foreach (PizzaTypeVM pizza in PizzasToTest)
                        {
                            if (CheckForMeat(pizza.LisasInt))
                            {
                                Pizzas.Add(pizza);
                            }
                        
                        }
                    }
                    if (Category == "Meat")
                    {
                        foreach (PizzaTypeVM pizza in PizzasToTest)
                        {
                            if (!CheckForMeat(pizza.LisasInt))
                            {
                                Pizzas.Add(pizza);
                            }

                        }
                    }

                }

            }
        }

        public bool CheckForMeat(List<int> pList)
        {
            foreach (var meat in _Meat)
            {
                if (pList.Contains(meat))
                {
                    return false;
                }
            }

            return true;

        }

        public async Task<IActionResult> OnPostChange()
        {
            await _context.SaveChangesAsync();
            return Redirect("./Index?category=" + Request.Form["mode"] + (orderID != 0 ? "&orderId=" + orderID : ""));
        }

        public string GetClass(string mode)
        {
            if (mode == Category)
            {
                return "active";
            }

            return "";

        }
    }
}

Pizza/Pages/Ostukorv.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL;
using Domain.ConnectModels;
using Domain.Models;
using Domain.VmModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Pizza.Pages
{
    public class OstukorvModel : PageModel
    {

        public List<POrderVM> POrderVms = new List<POrderVM>();
        public int orderID;

        private readonly PizzaDbContext _context;

        public OstukorvModel(PizzaDbContext context)
        {
            _context = context;
        }

        public void OnGet(int orderId)
        {
            orderID = orderId;
            if (_context.POrderOrderAssignments != null)
            {
                foreach (POrderOrderAssignment order in _context.POrderOrderAssignments.Where(x => x.OrderId == orderId))
                {
                    POrderVM pOrderVm = new POrderVM();
                    if (_context.POrders != null)
                    {
                        pOrderVm.POrder = _context.POrders.Single(x => x.Id == order.POrderId);
                        if (_context.PizzaTypes != null)
                        {
                            PizzaType pizzaType = _context.PizzaTypes.Single(x => x.Id == pOrderVm.POrder.PizzaTypeId);
                            pOrderVm.PizzaType = pizzaType;
                            pOrderVm.Value += pizzaType.Value * GetSizeInInt(pOrderVm.POrder.Size);
                            pOrderVm.Name?.Add(pizzaType.Name + " " + GetSizeInStr(pOrderVm.POrder.Size));
                        }

                    }

                    if (_context.POrderLisaAssignments != null)
                    {
                        var pizzaLisad = _context.POrderLisaAssignments
                            .Where(x => x.POrderId == orderId)
                            .Include(x => x.Lisa)
                            .ToList();

                        List<AddedLisaVM> AddedLisas = new List<AddedLisaVM>();
                        foreach (POrderLisaAssignment pizzaLisa in pizzaLisad)
                        {

                            if (AddedLisas.Where(x => x.Lisa?.Id == pizzaLisa.LisaId).Any() != true)
                            {
                                var newAddLisa = new AddedLisaVM();
                                newAddLisa.Lisa = pizzaLisa.Lisa;
                                newAddLisa.Count++;
                                AddedLisas.Add(newAddLisa);
                            }
                            else
                            {
                                AddedLisas.Single(x => x.Lisa == pizzaLisa.Lisa).Count++;
                            }

                        }

                        if (AddedLisas.Count != 0) 
                        {
                            pOrderVm.Name?.Add("+");
                        }
                        
                        List<string> striList = new List<string>();

                        foreach (AddedLisaVM pizzaLisa in AddedLisas)
                        {
                            if (pizzaLisa.Lisa != null)
                            {
                                pizzaLisa.TotalValue += pizzaLisa.Count * pizzaLisa.Lisa.Value;
                                pOrderVm.Value += pizzaLisa.Count * pizzaLisa.Lisa.Value;
                                striList.Add(pizzaLisa.Count + " x " + pizzaLisa.Lisa.Name);
                            }
                        }
                        pOrderVm.Name?.Add(string.Join(", ", striList));
                    }
                    POrderVms.Add(pOrderVm);
                }
            }
        }

        public async Task<IActionResult> OnPostSubmit()
        {
            int str = int.Parse(Request.Form["order"]);
            int pOrderCount = 0;
            int unPaid = 0;
            if (_context.POrderOrderAssignments != null)
            {
                List<POrderOrderAssignment> orders = _context.POrderOrderAssignments.Where(x => x.OrderId == str)
                    .Include(x => x.POrder).ToList();
                foreach (POrderOrderAssignment order in orders)
                {

                    if (Request.Form["pay_" + order.POrderId] == "on")
                    {
                        unPaid++;
                        if (order.POrder != null)
                        {
                            order.POrder.IsPaid = true;
                            pOrderCount++;
                        }
                        
                    }

                }
            }
            await _context.SaveChangesAsync();

            
            if (unPaid == pOrderCount && pOrderCount != 0) 
            {
                return Redirect(".");
            }
            return Redirect("./Ostukorv?orderId=" + str);
        }
        public async Task<IActionResult> OnPostDelete(int pOrderID)
        {
            int str = int.Parse(Request.Form["order"]);

            if (_context.POrderOrderAssignments != null && _context.POrders != null && _context.POrderLisaAssignments != null)
            {
                List<POrderOrderAssignment> orders = _context.POrderOrderAssignments.Where(x => x.POrderId == pOrderID).ToList();
                List<POrder> pOrders = _context.POrders.Where(x => x.Id == pOrderID).ToList();
                List<POrderLisaAssignment> pOrderLisaAssignments = _context.POrderLisaAssignments.Where(x=>x.POrderId == pOrderID).ToList();

                _context.POrders.RemoveRange(pOrders);
                _context.POrderOrderAssignments.RemoveRange(orders);
                _context.POrderLisaAssignments.RemoveRange(pOrderLisaAssignments);

            }

            await _context.SaveChangesAsync();
            return Redirect("./Ostukorv?orderId=" + str);
        }

        public string GetSizeInStr(PizzaSize size)
        {
            if (size == PizzaSize.Small)
            {
                return "Small";
            }

            if (size == PizzaSize.Medium)
            {
                return "Medium";
            }

            return "Big";
        }
        public double GetSizeInInt(PizzaSize size)
        {
            if (size == PizzaSize.Small)
            {
                return 1;
            }

            if (size == PizzaSize.Medium)
            {
                return 1.5;
            }

            return 3;
        }
    }
}

Pizza/Pages/PizzaKokku.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL;
using Domain.ConnectModels;
using Domain.Models;
using Domain.VmModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Pizza.Pages
{
    public class PizzaKokkuModel : PageModel
    {
        public POrderVM POrderVm = new POrderVM();

        private readonly PizzaDbContext _context;

        public int orderID = 0;

        public PizzaKokkuModel(PizzaDbContext context)
        {
            _context = context;
        }

        public void OnGet(int pOrderId, int? orderId)
        {

            if (orderId != null) 
            {
                orderID = orderId.Value; 
            }

            if (_context.POrders != null)
            {
                POrderVm.POrder = _context.POrders.Single(x => x.Id == pOrderId);
                if (_context.PizzaTypes != null)
                {
                    PizzaType pizzaType = _context.PizzaTypes.Single(x => x.Id == POrderVm.POrder.PizzaTypeId);
                    POrderVm.PizzaType = pizzaType;
                    POrderVm.Value += pizzaType.Value * GetSizeInInt(POrderVm.POrder.Size);
                    POrderVm.Name.Add(pizzaType.Name + " " + GetSizeInStr(POrderVm.POrder.Size));
                }
            }

            if (_context.POrderLisaAssignments != null)
            {
                var pizzaLisad = _context.POrderLisaAssignments.Where(x => x.POrderId == pOrderId)
                    .Include(x=>x.Lisa).ToList();

                List<AddedLisaVM> AddedLisas = new List<AddedLisaVM>();
                foreach (POrderLisaAssignment pizzaLisa in pizzaLisad)
                {

                    if (AddedLisas.Where(x => x.Lisa?.Id == pizzaLisa.LisaId).Any() != true)
                    {
                        var newAddLisa = new AddedLisaVM();
                        newAddLisa.Lisa = pizzaLisa.Lisa;
                        newAddLisa.Count++;
                        AddedLisas.Add(newAddLisa);
                    }
                    else
                    {
                        AddedLisas.Single(x => x.Lisa == pizzaLisa.Lisa).Count++;
                    }

                }

                foreach (AddedLisaVM pizzaLisa in AddedLisas)
                {
                    if (pizzaLisa.Lisa != null)
                    {
                        pizzaLisa.TotalValue += pizzaLisa.Count * pizzaLisa.Lisa.Value;
                        POrderVm.Value += pizzaLisa.Count * pizzaLisa.Lisa.Value;
                    }
                }

                POrderVm.AddedLisaVms = AddedLisas;
            }
        }

        public async Task<IActionResult> OnPostSubmit()
        {
            int OrderToCreateID = int.Parse(Request.Form["orderid"]);
            if (OrderToCreateID == 0 ) 
            {
                _context.Orders?.Add(new Order());
                _context.SaveChanges();
                if (_context.Orders != null) 
                {
                    OrderToCreateID = _context.Orders.Count();
                }
                
            }
            

            if (_context.Orders != null)
            {
                POrderOrderAssignment newPOrderOrderAssignment = new POrderOrderAssignment()
                {
                    OrderId = OrderToCreateID,
                    POrderId = int.Parse(Request.Form["id"])
                };
                _context.POrderOrderAssignments?.Add(newPOrderOrderAssignment);
                await _context.SaveChangesAsync();
                return Redirect("./Ostukorv?orderId=" + _context.Orders.Count());
            }

            await _context.SaveChangesAsync();
            return Redirect("./Ostukorv?orderId=" + 1);
        }

        public string GetSizeInStr(PizzaSize size)
        {
            if (size == PizzaSize.Small)
            {
                return "Small";
            }

            if (size == PizzaSize.Medium)
            {
                return "Medium";
            }

            return "Big";
        }
        public double GetSizeInInt(PizzaSize size)
        {
            if (size == PizzaSize.Small)
            {
                return 1;
            }

            if (size == PizzaSize.Medium)
            {
                return 1.5;
            }

            return 3;
        }
    }
}

Pizza/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Pizza.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pizza/Pages/Index.cshtml
@page
@model IndexModel
@using Domain.VmModels;
@using Domain.Models
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    
    <div class="row">
        <div class="col-3">
            <div class="row">
                <div class="col-lg-auto">
                    <div class="list-group">
                        <div>
                            <form method="post" class="text-center">
                                <button class="list-group-item @Model.GetClass("Cheese")" asp-page-handler="Change">
                                    Cheese
                                </button>
                                <input type="hidden" name="mode" value="Cheese" />
                            </form>
                            <form method="post" class="text-center">
                                <button class="list-group-item @Model.GetClass("Vegan")" asp-page-handler="Change">
                                    Vegan
                                </button>
                                <input type="hidden" name="mode" value="Vegan" />
                            </form>
                            <form method="post" class="text-center">
                                <button class="list-group-item @Model.GetClass("Meat")" asp-page-handler="Change">
                                    Meat
                                </button>
                                <input type="hidden" name="mode" value="Meat" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-9">
            <div class="row">
                @foreach (PizzaTypeVM Pizza in Model.Pizzas)
                {
                    <div class="col-lg-3">
                        <div class="card h-100">
                            <div class="card-body">
                                <h4 class="card-title">
                                    @if (Model.orderID != 0)
                                    {
                                        <a asp-page="PizzaSettings"
                                           asp-route-orderId="@Model.orderID"
                                           asp-route-pizzaId="@Pizza.PizzaType?.Id">@Pizza.PizzaType?.Name</a>
                                    }
                                    else
                                    {
                                        <a asp-page="PizzaSettings"
                                         asp-route-pizzaId="@Pizza.PizzaType?.Id">@Pizza.PizzaType?.Name</a>
                                    }
                                </h4>
                                <p class="card-text">
                                    @Pizza.NameLisas
                                </p>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    
</div>

Pizza/Pages/Ostukorv.cshtml
@page
@using Domain.VmModels
@model Pizza.Pages.OstukorvModel
@{
}

<br />
<form method="post">
    @foreach (POrderVM order in Model.POrderVms)
    {
        if (!order.POrder.IsPaid)
        {
        <div class="row">
            <div class="col-1"><input name="pay_@order.POrder.Id" id="@order.POrder.Id" tpl-checked="yes" type="checkbox" /></div>
            <div class="col-5 border border-success">@string.Join(" ", order.Name)</div>
            <div class="col-3 border border-success">@order.Value</div>
            <div class="col-3"><button class="btn btn-danger" asp-page-handler="Delete" asp-route-pOrderID="@order.POrder.Id">Delete</button></div>
            <input type="hidden" name="orderToDelete_@order.POrder.Id" value="@order.POrder.Id" />
        </div>
        }
    }
    <br />

    <div class="row">
        <div class="col-lg-2">
            <a class="btn btn-outline-primary" asp-page="Index" asp-route-orderId="@Model.orderID">Back to Index</a>
        </div>
        <div class="col-lg-1">
            <button class="btn btn-outline-success" asp-page-handler="Submit">Pay</button>
            <input type="hidden" name="order" value="@Model.orderID" />
        </div>
    </div>
</form>

Pizza/Pages/PizzaKokku.cshtml
@page
@using Domain.VmModels
@model Pizza.Pages.PizzaKokkuModel
@{
}

<div class="row">
    <table class="table table-bordered">

        <thead>
        </thead>
        <tbody>
        <tr>
            <th>@Model.POrderVm.Name[0]</th>
            <td>+@(Model.POrderVm.PizzaType.Value * Model.GetSizeInInt(Model.POrderVm.POrder.Size))</td>
        </tr>
        @foreach (AddedLisaVM lisa in Model.POrderVm.AddedLisaVms)
        {
            <tr>
                <th>@(lisa.Count + " x " + lisa.Lisa?.Name)</th>
                <td>+@lisa.TotalValue</td>
            </tr>
        }
        <tr class="table-success">
            <th>Hind</th>
            <td>@Model.POrderVm.Value</td>
        </tr>
        </tbody>
    </table>
</div>

    <div class="row">
        <div class="col-lg-11">
            <form method="post">
                <button class="btn btn-outline-success" asp-page-handler="Submit">Go to shopping cart</button>
                <input type="hidden" name="id" value="@Model.POrderVm.POrder.Id" />
                <input type="hidden" name="orderid" value="@Model.orderID" />
            </form>
        </div>
    </div>

Pizza/Pages/PizzaSettings.cshtml
@page
@using Domain.Models
@using Domain.VmModels
@model Pizza.Pages.PizzaSettingsModel
@{
}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="my-4">@Model.PizzaType.Name</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h2 class="my-4">Suurus</h2>
            <form method="post">
                <div class="row">
                    <div class="col-auto">
                        <button class="btn @Model.getClass("S")" asp-page-handler="DropSm">Small</button>
                        <input type="hidden" name="small" value="Small" />
                    </div>
                    <div class="col-auto">
                        <button class="btn @Model.getClass("M")" asp-page-handler="DropMm">Medium</button>
                        <input type="hidden" name="medium" value="Medium" />
                    </div>
                    <div class="col-auto">
                        <button class="btn @Model.getClass("B")" asp-page-handler="DropBg">Big</button>
                        <input type="hidden" name="big" value="Big" />
                        <input type="hidden" name="orderid" value="@Model.orderID" />
                    </div>
                </div>
                
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <h2 class="my-4">Sisaldab</h2>
            <div class="list-group">
                @foreach (AddedLisaVM addedLisa in Model.AddedLisas)
                {
                    <a href="#" class="list-group-item">@(addedLisa.Count + " x " + addedLisa.Lisa?.Name)</a>
                }
            </div>
        </div>
        <div class="col-lg-6">
            <h2 class="my-4">Lisandid</h2>
            <div class="row">
                @foreach (Lisa lisa in Model.Lisas)
                {
                    <form method="post">
                        <div class="col-auto m-2">
                            <button class="btn btn-outline-success" asp-page-handler="Submit">@lisa.Name</button>
                            <input type="hidden" name="id" value="@lisa.Id" />
                            <input type="hidden" name="orderid" value="@Model.orderID" />
                        </div>
                    </form>
                }
                </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-lg-12">
            @if (Model.orderID != 0)
            {
                <button type="button" class="btn btn-outline-success" onclick="window.location='/PizzaKokku?pOrderId=' + @Model.pizzaOrder.Id + '&orderId=' + @Model.orderID">Next</button>
            }
            else
            {
                <button type="button" class="btn btn-outline-success" onclick="window.location='/PizzaKokku?pOrderId=' + @Model.pizzaOrder.Id">Next</button>
            }

        </div>
    </div>

Pizza/Pages/Statistics.cshtml
@page
@using Domain.VmModels
@model Pizza.Pages.StatisticsModel
@{
}

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Number of pizza</th>
                <th scope="col">Pizza Name</th>
                <th scope="col">Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach (StatVM stat in Model.StatVMS)
            {
                <tr>
                    <td>@stat.PizzaCount</td>
                    <td>@stat.PizzaTypeName</td>
                    <td>@stat.Value</td>
                </tr>
            }

            <tr class="table-success">
                <th colspan="2">@Model.StatVMS.Sum(x=>x.PizzaCount)</th>
                <th>@Model.StatVMS.Sum(x => x.Value)</th>
            </tr>
        </tbody>
    </table>
</div>